WIP
bookmebus/spree_active_sale pull request #34
Opened 2021-08-30 16:49 UTC by sokmesakhiev

2021-09-03 14:56 UTC, channainfo requested changes

2021-09-03 14:56 UTC, channainfo commented on app/controllers/spree/admin/active_sale_events_controller.rb
> +          CreatePromotion.call(active_sale_event: @object)
let's move the logic to ActiveSaleEventCreator/Updater service and remove after_action.

2021-09-03 14:56 UTC, channainfo commented on app/controllers/spree/admin/sale_products_controller.rb
> +      def create_product_promotion_rule
let create new services to handle this instead of using controller callback.

2021-09-09 03:04 UTC, channainfo requested changes

2021-09-09 13:19 UTC, sokmesakhiev commented on app/controllers/spree/admin/active_sale_events_controller.rb
> +        ActiveSaleEventDestroyer.call(active_sale_event: @active_sale_event)
Spree doing destroy for promotion so i believe it should play the same to promotion

2021-09-09 14:06 UTC, merged