Close #47 fix conflict name space active sale
bookmebus/spree_active_sale pull request #48
Opened 2021-09-17 16:12 UTC by sokmesakhiev

2021-09-19 14:59 UTC, channainfo requested changes

2021-09-19 14:59 UTC, channainfo commented on app/controllers/spree/admin/active_sale_events_controller.rb
> +        context = ActiveSales::ActiveSaleEventCreator.call(params: active_sale_event_params)
@sokmesakhiev why do we need to use **ActiveSales** plural as a module?

2021-09-20 13:00 UTC, sokmesakhiev commented on app/controllers/spree/admin/active_sale_events_controller.rb
> +        context = ActiveSales::ActiveSaleEventCreator.call(params: active_sale_event_params)
It will conflict with ActiveSale model that one is class and one is module

2021-09-20 13:02 UTC, sokmesakhiev commented on app/controllers/spree/admin/active_sale_events_controller.rb
> +        context = ActiveSales::ActiveSaleEventCreator.call(params: active_sale_event_params)
Maybe it is good to have a namespace as Flash Sale instead of ActiveSale

2021-09-20 14:11 UTC, merged